name: update_platforms 

on: 
    push:
        paths:
            - setup/R/get_platforms.R 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true

    - name: Set up R 
      uses: r-lib/actions/setup-r@v1

    - name: install libcurl
      run: sudo apt-get install libcurl4-openssl-dev

    - name: Install remotes 
      run: |
          install.packages('remotes')
      shell: Rscript {0}

    - name: Cache R packages
      id: cache-packages
      uses: actions/cache@v2
      with:
            path: ${{ env.R_LIBS_USER }}
            key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-GEOquery-1

    - name: Query dependencies
      run: |
          remotes::install_bioc('GEOquery')
          remotes::install_cran('BiocManager')
          BiocManager::install('org.Hs.eg.db')
      shell: Rscript {0}

    - name: Test get_platforms.R 
      run: Rscript setup/R/get_platforms.R
 
